name = "sitemap-processor"
main = "src/worker.ts"
compatibility_date = "2023-05-18"

[[d1_databases]]
binding = "DB"
database_name = "urls"
database_id = "5c6798d5-e875-4972-b119-a1bf179497be"

[triggers]
crons = ["0 0 * * *"] # Run daily at midnight UTC

